language: shell

os:
  - linux

vm:
  size: x-large

branches:
  only:
  - dig

env:
  jobs:
    - TORCH_VERSION=1.6.0 PYTHON_VERSION=3.8 IDX=cpu

install:
  - source script/conda.sh
  - conda create --yes -n test python="${PYTHON_VERSION}"
  - source activate test
  - conda install pytorch==${TORCH_VERSION} ${TOOLKIT} -c pytorch -c conda-forge --yes
  - conda install -c conda-forge rdkit --yes
  - pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-${TORCH_VERSION}+${IDX}.html
  - pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-${TORCH_VERSION}+${IDX}.html
  - pip install torch-cluster -f https://pytorch-geometric.com/whl/torch-${TORCH_VERSION}+${IDX}.html
  - pip install torch-spline-conv -f https://pytorch-geometric.com/whl/torch-${TORCH_VERSION}+${IDX}.html
  - pip install furo
  - pip install numpy
  - pip install sphinx==3.5.4
  - pip install sphinx_rtd_theme==0.5.2
  - pip install torch-geometric==1.7.0
  - pip install git+https://github.com/Chilipp/autodocsumm.git
  - pip install captum==0.2.0
  - pip install cilog
  - pip install typed-argument-parser==1.5.4 
  - pip install tensorboard
  - python setup.py install

script:
  - python setup.py test

# after_success:
#   - codecov

notifications:
  email: false