explanation_result_dir: ''
sparsity: 0.5
param:
  bbbp:
    lr: 0.01
    epochs: 1000
    coff_size: 0.001
    coff_ent: 1e-5
  ba_shapes:
    lr: 0.01
    epochs: 100
    coff_size: 0.1
    coff_ent: 0.1
  graph_sst2:
    lr: 0.01
    epochs: 1000
    coff_size: 0.001
    coff_ent: 1e-5
  graph_sst5:
    lr: 0.01
    epochs: 1000
    coff_size: 0.001
    coff_ent: 1e-5
  twitter:
    lr: 0.01
    epochs: 1000
    coff_size: 0.001
    coff_ent: 1e-5
  ba_2motifs:
    lr: 0.02
    epochs: 100
    coff_size: 0.001
    coff_ent: 1e-5